### ISSUE TITLE
Is this library kept up-to-date?

### ISSUE THREAD

**Issue by jsfan3** [diamonddevgroup/CN1-Device#1]
Thank you very much for this CN1Lib.
Is this library kept up-to-date?

**Comment by diamondobama** [comment]
Updated the device list for [Android](https://github.com/diamonddevgroup/CN1-Device/commit/61f88c282d31214a9bf743e5c46adc33d2c46f84) and [iOS](https://github.com/diamonddevgroup/CN1-Device/commit/b407317cc4927cc98da3b75f18ec7a94660edc43)

**Comment by diamondobama** [comment]
A [pull request](https://github.com/codenameone/CodenameOneLibs/pull/21) has also been made to make it available in CN1 marketplace

**Comment by jsfan3** [comment]
Thank you!
