### ISSUE TITLE
Something went wrong in the update you done 20 days ago

### ISSUE THREAD

**Issue by jsfan3** [diamonddevgroup/CN1-Device#2]
Something went wrong in the update you done 20 days ago.
In my CN1 project, I've done "Refresh CN1Lib files" several times, but the file `/lib/Device.ver` still contains `version=1`, so no updated is done.
Can you please do a check? Thank you

**Comment by codenameone** [comment]
Refresh cn1lib doesn't bring a new version. You need to open the extension manager and explicitly update the lib.

**Comment by jsfan3** [comment]
You're right, thank you, your suggestion solved my problem.
