### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jsfan3** [diamonddevgroup/CN1-Device#6]
Could you update the library?
Do you think there is a way to automate the updating of supported devices?

**Comment by diamondobama** [comment]
For Android, 
Yes, there is. Instead of manually updating the device list, I could periodically download the device list in real-time on the users' phones. This means offline apps may no longer use this lib.

As for iOS,
I don't think it's possible as the name is manually created. Unlike Google, Apple doesn't have a central repo for this.

I'm open to any suggestions.

What I could do now is to set a reminder to update the list monthly and create a CN1Lib.

**Comment by jsfan3** [comment]
I think if you can keep this cn1lib updated on a monthly basis to include new Android and Apple models coming out, that's enough. I hope this is easy for you to do.

Otherwise, any other approach should be considered carefully, because it would change the requirements and the way this cn1lib works. 

In theory, I suppose it would be possible to create a different cn1lib that acts differently, offering a method to download the list of known devices, in addition to the other methods that already exist. The developer will be able to invoke the method to download the list of known devices at the first start of the app or when he wants to: if the device will be identified, there will be no more need to download that list; if the device will not be identified (because too recent), it will be the developer's responsibility to write a code to download again the list of known devices after one month.

Leaving the cn1lib as it is, we developers must remember to update it. With a cn1lib that offers a method to download the list of devices, this list can always be updated, without the need to keep the cn1lib updated and without the need to upload a new version of the app every month in stores.

Any of these options, however, will require some work on your part.

A completely different strategy, would be to offer a REST service that, given an identifier sent by the device, allows to get in response brand and model. This approach would make the cn1lib very light, as it would only have to make a REST call. On the other hand, there should be an online service that is always up-to-date and offers such a REST API. The latter option is the most difficult and expensive to implement.

Of all these options, probably the easiest is to keep the existing cn1lib as it is, updating it on a monthly basis.

**Comment by diamondobama** [comment]
Thanks for your proposed solutions. I will look into those.

I've updated the library and submitted it to Codename One for approval. 

I have released a [new version](https://github.com/diamonddevgroup/CN1-Device/releases/tag/6.0).

Google has changed things up a bit and if you perhaps have an Android device lying around, could you please test this library (using this [binary](https://github.com/diamonddevgroup/CN1-Device/releases/download/6.0/Device.cn1lib)) to see that it still behaves as expected? I currently don't have an Android device at home.

**Comment by jsfan3** [comment]
Thank you!
I've just updated to the version 6 of your CN1lib and I confirm that it work with my Samsung Android 10 device. I update the binary using the Codename One Extension Manager, however I used the `diff` utility to be sure that the binary is the same you linked.

**Comment by jsfan3** [comment]
I’ve just discovered that doesn’t compile on iOS. This is the copy of the chat with the Codename One technical support:

The error says that it is having trouble reading the DeviceList.plist file. That cn1lib was just updated yesterday with changes to the DeviceList.plist.
https://github.com/diamonddevgroup/CN1-Device/commit/ff7faaec464448e62900cc79fddb71f581773ed4#diff-cba7be261212cea90d65f87c7ac8fbe0
If you are using his latest, then likely that commit has a problem. If you aren't using his latest, I suggest trying to update to the latest version of CN1-Device cn1lib.

The pertinent line from the error log was:
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build5280865988832284838xxx/dist/MainClass-src/DeviceList.plist
error: unable to read input file as a property list: The operation couldnâ€™t be completed. (XCBUtil.PropertyListConversionError error 1.) (in target 'MainClass' from project 'MainClass')

**Comment by diamondobama** [comment]
@jsfan3, I resolved the issue [here](https://github.com/diamonddevgroup/CN1-Device/commit/224905b5990c9e422b5e9f0a7179168380c0d49e), but before I submit an update to CN1's extensions store, could you perhaps test again using this file and let me know if it works, please.

I had to zip it up because GitHub doesn't support attaching binary files. Please extract.

[Device.zip](https://github.com/diamonddevgroup/CN1-Device/files/4693897/Device.zip)

**Comment by jsfan3** [comment]
Good news: now it compiles, thank you :)

**Comment by diamondobama** [comment]
Thanks :)
